CREATE DATABASE INFOPUB;
USE INFOPUB;

CREATE TABLE EMPLEADO(
    DNI_EMPLEADO VARCHAR(9) PRIMARY KEY NOT NULL,
    NOMBRE VARCHAR(45) NOT NULL,
    DOMICILIO VARCHAR(45)
);

CREATE TABLE LOCALIDAD(
    COD_LOCALIDAD INT PRIMARY KEY NOT NULL,
    NOMBRE VARCHAR(45) NOT NULL
);

CREATE TABLE PUB(
    COD_PUB VARCHAR(9) PRIMARY KEY NOT NULL,
    NOMBRE VARCHAR(45) NOT NULL,
    LICENCIA_FISCAL VARCHAR(45) NOT NULL,
    DOMICILIO VARCHAR(45),
    FECHA_APERTURA DATE NOT NULL,
    HORARIO VARCHAR(4) NOT NULL,
    COD_LOCALIDAD INT NOT NULL
);

CREATE TABLE EXISTENCIAS(
    COD_ARTICULO VARCHAR(10) PRIMARY KEY NOT NULL,
    NOMBRE VARCHAR(45) NOT NULL,
    CANTIDAD INT NOT NULL,
    PRECIO INT NOT NULL,
    COD_PUB VARCHAR(9) NOT NULL
);

CREATE TABLE TITULAR(
    DNI_TITULAR VARCHAR(9) NOT NULL,
    NOMBRE VARCHAR(45) NOT NULL,
    DOMICILIO VARCHAR(45),
    COD_PUB VARCHAR(9) NOT NULL
);

CREATE TABLE PUB_EMPLEADO(
    COD_PUB VARCHAR(9) NOT NULL,
    DNI_EMPLEADO VARCHAR(9) NOT NULL,
    FUNCION VARCHAR(20) NOT NULL
);

-- RESTRICCIONES
ALTER TABLE PUB_EMPLEADO ADD CONSTRAINT PK_PUB_EMPLEADO
PRIMARY KEY(COD_PUB,DNI_EMPLEADO,FUNCION);

ALTER TABLE PUB ADD CONSTRAINT FK_PUB_LOCALIDAD
    FOREIGN KEY (COD_LOCALIDAD)
    REFERENCES LOCALIDAD(COD_LOCALIDAD);

ALTER TABLE EXISTENCIAS ADD CONSTRAINT FK_EXISTENCIAS_PUB
FOREIGN KEY (COD_PUB)
REFERENCES PUB(COD_PUB);

ALTER TABLE TITULAR ADD CONSTRAINT FK_TITULAR_PUB
FOREIGN KEY (COD_PUB)
REFERENCES PUB (COD_PUB);

ALTER TABLE PUB_EMPLEADO ADD CONSTRAINT FK_PUBEMPLE_PUB
Foreign Key (COD_PUB) REFERENCES PUB(COD_PUB);

ALTER TABLE PUB_EMPLEADO ADD CONSTRAINT FK_PUBEMPLE_EMPLEADO
Foreign Key (DNI_EMPLEADO) REFERENCES EMPLEADO(DNI_EMPLEADO);

ALTER TABLE PUB ADD CONSTRAINT CK_HORARIO
CHECK(HORARIO IN('HOR1','HOR2','HOR3'));

ALTER TABLE EXISTENCIAS ADD CONSTRAINT CK_PRECIO
CHECK(PRECIO != 0);

ALTER TABLE PUB_EMPLEADO ADD CONSTRAINT CK_FUNCION
CHECK(FUNCION IN('CAMARERO','SEGURIDAD','LIMPIEZA'));

-- AÑADIMOS DATOS A LAS TABLAS
INSERT INTO empleado (DNI_EMPLEADO,NOMBRE,DOMICILIO) VALUES ('75445155J','GERARDO SANZ','C/.LOS FUEROS 6');
INSERT INTO empleado (DNI_EMPLEADO,NOMBRE,DOMICILIO) VALUES ('30112541G','FELIPE CASTILLO','AV. GRAN VIA 23');
INSERT INTO empleado (DNI_EMPLEADO,NOMBRE,DOMICILIO) VALUES ('16054525S','ANGIE TREJO','C/.ARENE 25');
