-- Active: 1673602447684@@127.0.0.1@3306@shows
CREATE DATABASE SHOWS;
USE SHOWS;

-- CREACION DE LAS TABLAS
CREATE TABLE ESPECTACULOS(
    COD_ESPECTACULO VARCHAR(10) NOT NULL,
    NOMBRE VARCHAR (45) NOT NULL,
    TIPO VARCHAR(45) NOT NULL,
    FECHA_INICIAL DATE,
    FECHA_FINAL DATE,
    INTERPRETE VARCHAR(45) NOT NULL,
    COD_RECINTO VARCHAR(10)
); 

CREATE TABLE PRECIOS_ESPECTACULOS(
    COD_ESPECTACULO VARCHAR(10) NOT NULL,
    COD_RECINTO VARCHAR(10) NOT NULL,
    ZONA VARCHAR(45) NOT NULL,
    PRECIO DECIMAL NOT NULL
);

CREATE TABLE RECINTOS(
    COD_RECINTO VARCHAR(10) NOT NULL,
    NOMBRE VARCHAR(45) NOT NULL,
    DIRECCION VARCHAR(45) NOT NULL,
    CIUDAD VARCHAR(45) NOT NULL,
    TELEFONO INT(9),
    HORARIO VARCHAR(45) NOT NULL
);

CREATE TABLE ZONAS_RECINTOS(
    COD_RECINTO VARCHAR(10)NOT NULL,
    ZONA VARCHAR(45) NOT NULL,
    CAPACIDAD INT NOT NULL
);

CREATE TABLE ASIENTOS(
    COD_RECINTO VARCHAR(10)NOT NULL,
    ZONA VARCHAR(45) NOT NULL,
    FILA INT NOT NULL,
    NUMERO INT NOT NULL
);

CREATE TABLE REPRESENTACIONES(
    COD_ESPECTACULO VARCHAR(10) NOT NULL,
    FECHA DATE NOT NULL,
    HORA VARCHAR(8) NOT NULL
);

CREATE TABLE ENTRADAS(
    COD_ESPECTACULO VARCHAR(10)NOT NULL,
    FECHA DATE NOT NULL,
    HORA VARCHAR(8) NOT NULL,
    COD_RECINTO VARCHAR(10) NOT NULL,
    FILA INT,
    NUMERO INT,
    ZONA VARCHAR(45),
    DNI_CLIENTE VARCHAR(9)
);

CREATE TABLE ESPECTADORES(
    DNI_CLIENTE VARCHAR(9) NOT NULL,
    NOMBRE VARCHAR(45)NOT NULL,
    DIRECCION VARCHAR(45),
    TELEFONO INT(9),
    CIUDAD VARCHAR(45),
    NTARJETA VARCHAR(20)NOT NULL
);

-- RESTRICCIONES DE LAS TABLAS(CLAVE PRIMARIA)
ALTER TABLE espectaculos ADD CONSTRAINT PK_ESPECTACULOS
PRIMARY KEY(COD_ESPECTACULO);

ALTER TABLE precios_espectaculos 
ADD CONSTRAINT PK_PRECIOS_ESPECTACULOS
PRIMARY KEY(COD_ESPECTACULO, COD_RECINTO, ZONA);

ALTER TABLE recintos ADD CONSTRAINT PK_RECINTOS
PRIMARY KEY(COD_RECINTO);

ALTER TABLE zonas_recintos ADD CONSTRAINT PK_ZONAS_RECINTOS
PRIMARY KEY(COD_RECINTO,ZONA);

ALTER TABLE asientos ADD CONSTRAINT PK_ASIENTOS
PRIMARY KEY(COD_RECINTO,ZONA,FILA,NUMERO);

ALTER TABLE representaciones ADD CONSTRAINT PK_REPRESENTACIONES
PRIMARY KEY(COD_ESPECTACULO,FECHA,HORA);

ALTER TABLE espectaculos ADD CONSTRAINT PK_ESPECTACULOS
PRIMARY KEY(COD_ESPECTACULO);

ALTER TABLE entradas ADD CONSTRAINT PK_ENTRADAS
PRIMARY KEY(COD_ESPECTACULO,FECHA,HORA,FILA,NUMERO,ZONA,DNI_CLIENTE);

ALTER TABLE espectadores ADD CONSTRAINT PK_ESPECTADORES
PRIMARY KEY(DNI_CLIENTE);

-- RESTRICCIONES DE LAS TABLAS(CLAVE FORANEA)

ALTER TABLE espectaculos 
ADD CONSTRAINT FK_ESPECTACULOS_RECIENTOS
Foreign Key (COD_RECINTO) REFERENCES recintos(COD_RECINTO);

ALTER TABLE precios_espectaculos
ADD CONSTRAINT FK_PRECIOESPEC_ESPECTACULOS
Foreign Key (COD_ESPECTACULO) REFERENCES espectaculos(COD_ESPECTACULO);

ALTER TABLE zonas_recintos
ADD CONSTRAINT FK_ZONARECI_RECINTOS
Foreign Key (COD_RECINTO) REFERENCES recintos(COD_RECINTO);

ALTER TABLE precios_espectaculos 
ADD CONSTRAINT FK_PRECIOESPEC_RECINTOS
Foreign Key (COD_RECINTO,ZONA) REFERENCES zonas_recintos(COD_RECINTO,ZONA);

ALTER TABLE asientos
ADD CONSTRAINT FK_ASIENTOS_ZONAREC
Foreign Key (COD_RECINTO,ZONA) REFERENCES zonas_recintos(COD_RECINTO,ZONA);

ALTER TABLE representaciones
ADD CONSTRAINT FK_REPRE_ESPEC
Foreign Key (COD_ESPECTACULO) REFERENCES espectaculos(COD_ESPECTACULO);

ALTER TABLE ENTRADAS
ADD CONSTRAINT FK_ENTRADAS_ESPEC
Foreign Key (COD_ESPECTACULO) REFERENCES espectaculos(COD_ESPECTACULO);

ALTER TABLE ENTRADAS
ADD CONSTRAINT FK_ENTRADAS_ASIENTOS
Foreign Key (COD_RECINTO,ZONA,FILA,NUMERO) REFERENCES ASIENTOS(COD_RECINTO,ZONA,FILA,NUMERO);

ALTER TABLE ENTRADAS
ADD CONSTRAINT FK_ENTRADAS_ESPECTADOR
Foreign Key (DNI_CLIENTE) REFERENCES espectadores(DNI_CLIENTE);