-- Active: 1673602447684@@127.0.0.1@3306@ejer_empresa

-- Creacionde base de datos
CREATE DATABASE ejer_empresa;

-- Creacion de tablas
CREATE TABLE EMPLEADOS(
    DNI INT(8) NOT NULL,
    NOMBRE VARCHAR(10) NOT NULL,
    APELLIDO1 VARCHAR(15) NOT NULL,
    APELLIDO2 VARCHAR(15),
    DIRECC1 VARCHAR(25),
    DIRECC2 VARCHAR(20),
    CIUDAD VARCHAR(20),
    PROVINCIA VARCHAR(20),
    COD_POSTAL VARCHAR(5),
    SEXO VARCHAR(1),
    FECHA_NAC DATE
);

CREATE TABLE HISTORIAL_LABORAL(
    EMPLEADO_DNI INT(8) NOT NULL,
    TRABAJO_COD INT(5) NOT NULL,
    FECHA_INICIO DATE NOT NULL,
    FECHA_FIN DATE  ,
    DPTO_COD INT(5) ,
    SUPERVISOR_DNI INT(8)
);

CREATE TABLE HISTORIAL_SALARIAR(
    EMPLEADO_DNI INT(8) NOT NULL,
    SALARIO INT NOT NULL,
    FECHA_COMIENZO DATE NOT NULL,
    FECHA_FIN DATE
);

CREATE TABLE DEPARTAMENTO(
    DPTO_COD INT(5) NOT NULL,
    NOMBRE_DPTO VARCHAR(30) NOT NULL,
    DPTO_PADRE INT(5),
    PRESUPUESTO INT NOT NULL,
    PRES_ANUAL INT
);

CREATE TABLE ESTUDIO(
    EMPLEADO_DNI INT(8) NOT NULL,
    UNIVERSIDAD INT(5) ,
    AÑO INT,
    GRADO VARCHAR(3),
    ESPECIALIDAD VARCHAR(20)
);

CREATE TABLE UNIVERSIDAD(
    UNIV_COD INT(5) NOT NULL,
    NOMBRE_UNI VARCHAR(25),
    CUIDAD VARCHAR(20),
    MUNICIPIO VARCHAR(2),
    COD_POSTAL VARCHAR(5)
);

CREATE TABLE TRABAJOS(
    TRABAJO_COD INT(5) NOT NULL,
    NOMBRE_TRAB VARCHAR(20),
    SALARIO_MIN INT(2) NOT NULL,
    SALARIO_MAX INT(2) NOT NULL
);

                -- RESTRICCIONES DE LAS TABLAS
--SEXO SOLO ES H o M
ALTER TABLE empleados 
ADD CONSTRAINT CK_SEXO
CHECK(SEXO IN('H','M'));

--DOS DEPARTAMENTOS NO SE LLAMAN IGUAL
ALTER TABLE departamento
ADD CONSTRAINT UK_NOMBRE_DPTO
UNIQUE(NOMBRE_DPTO);

-- DOS TRABAJOS NO SE LLAMAN IGUAL
ALTER TABLE trabajos
ADD CONSTRAINT UK_NOMBRE_TRAB
UNIQUE(NOMBRE_TRAB);

-- CADA EMPLEADO TIENE UN SOLO SALARIO EN CADA MOMENTO
ALTER TABLE historial_salariar
ADD CONSTRAINT PK_HISTORIAL_SALARIAR
PRIMARY KEY (EMPLEADO_DNI,FECHA_COMIENZO);
-- CADA EMPLEADO TIENE ASIGNADO UN SOLO TRABAJO EN CADA MOMENTO
ALTER TABLE historial_laboral
ADD CONSTRAINT PK_HISTORIAL_LABORAL
PRIMARY KEY(EMPLEADO_DNI,FECHA_INICIO);

--CLAVES PRIMARIAS
ALTER TABLE empleados ADD CONSTRAINT PK_EMPLEADOS
PRIMARY KEY(DNI);

ALTER TABLE departamento ADD CONSTRAINT PK_DEPARTAMENTO
PRIMARY KEY(DPTO_COD);

ALTER TABLE estudio ADD CONSTRAINT PK_ESTUDIO
PRIMARY KEY(EMPLEADO_DNI);

ALTER TABLE universidad ADD CONSTRAINT PK_UNIVERSIDAD
PRIMARY KEY(UNIV_COD);

ALTER TABLE trabajos ADD CONSTRAINT PK_TRABAJOS
PRIMARY KEY(TRABAJO_COD);

-- CLAVES FORANEAS/SECUNDARIAS
ALTER TABLE estudio 
ADD CONSTRAINT FK_ESTUDIO_EMPLEADOS
Foreign Key (EMPLEADO_DNI) 
REFERENCES empleados(DNI);

ALTER TABLE estudio
ADD CONSTRAINT FK_ESTUDIO_UNIVERSIDAD
Foreign Key (universidad) 
REFERENCES universidad(UNIV_COD);

ALTER TABLE departamento
ADD CONSTRAINT FK_DPTO_PADRE
Foreign Key (DPTO_PADRE) 
REFERENCES departamento(DPTO_COD);

ALTER TABLE historial_salariar
ADD CONSTRAINT FK_HISTSAL_EMPLEADO
Foreign Key (EMPLEADO_DNI) 
REFERENCES empleados(DNI);

ALTER TABLE historial_laboral
ADD CONSTRAINT FK_HISTLAB_EMPLEADO
Foreign Key (EMPLEADO_DNI) 
REFERENCES empleados(DNI);

ALTER TABLE historial_laboral
ADD CONSTRAINT FK_HISTLAB_SUPERVISOR
Foreign Key (SUPERVISOR_DNI) 
REFERENCES empleados(DNI);

ALTER TABLE historial_laboral
ADD CONSTRAINT FK_HISTLAB_DEPA
Foreign Key (DPTO_COD) 
REFERENCES departamento(DPTO_COD);

ALTER TABLE historial_laboral
ADD CONSTRAINT FK_HISTLAB_TRABAJO
Foreign Key (TRABAJO_COD) 
REFERENCES trabajos(TRABAJO_COD);

-- INSERCION DE DATOS A LA TABLA EMPLEADOS
INSERT INTO empleados(
    DNI,NOMBRE,APELLIDO1,APELLIDO2,DIRECC1,DIRECC2,
    CIUDAD,PROVINCIA,COD_POSTAL,SEXO,FECHA_NAC)
    VALUES(
        16064451,'RAMIRO','PEREZ','SANDOVAL','C.FUEROS 12','AV.ALGORTA 11',
        'PAIS VASCO','VIZCAYA',48991,'H',19860520
    );
INSERT INTO empleados(
    DNI,NOMBRE,APELLIDO1,APELLIDO2,DIRECC1,DIRECC2,
    CIUDAD,PROVINCIA,COD_POSTAL,SEXO,FECHA_NAC)
    VALUES(
        74522855,'YOLANDA','SANZ','CHERO','ARENE BIDEA',NULL,
       'PAIS VASCO','VIZCAYA',48460,'M','1972-09-05'
    );

--INSERTAMOS DATOS PARA COMPROVAR LAS RESTRICCIONES
INSERT INTO empleados(
    DNI,NOMBRE,APELLIDO1,APELLIDO2,SEXO)
    VALUES(111222,'SERGIO','PALMA','ENTRENA','P');
    --EL ERROR SERIA 'Check constraint 'CK_SEXO' is violated.'
INSERT INTO historial_laboral(
    EMPLEADO_DNI,TRABAJO_COD,FECHA_INICIO,FECHA_FIN,DPTO_COD,SUPERVISOR_DNI)
VALUES('111222',NULL,'6-JUN-1996',NULL,NULL,'222333');
    --EL ERROR ES QUE TRABAJO_COD NO PUEDE SER NULO ADEMAS Q NO EXISTE DATOS PARA SUPERVISOR_DNI

-- AÑADIR UN NUEVO ATRIBUTO "VALORACION" EN LA TABLA EMPLEADOS CON UN CHECK DE 1 A 10
ALTER TABLE empleados
ADD COLUMN VALORACION INT DEFAULT 5;
ALTER TABLE empleados
ADD CONSTRAINT CK_VALORACION
CHECK(VALORACION BETWEEN 1 AND 10);

-- CAMBIAR EL TIPO DE DATO DE LA TABLA EMPLEADOS
ALTER TABLE empleados 
MODIFY COLUMN FECHA_NAC VARCHAR(10);

--INSERCION DE DATOS EN LAS TABLAS UNIVERSIDAD Y ESTUDIOS
SELECT*FROM universidad;
INSERT INTO universidad(
    UNIV_COD,NOMBRE_UNI,CIUDAD)
    VALUES(05678,'UNISAPIENS','MALAGA');
INSERT INTO universidad(
    UNIV_COD,NOMBRE_UNI,CIUDAD)
    VALUES(14785,'UNIARISTOLES','MURCIA');
INSERT INTO universidad(
    UNIV_COD,NOMBRE_UNI,CIUDAD)
    VALUES(36985,'UPTV','BILBAO');
INSERT INTO universidad(
    UNIV_COD,NOMBRE_UNI,CIUDAD)
    VALUES(25879,'UTC','SEVILLA');

SELECT*FROM universidad;
INSERT INTO estudio(
    EMPLEADO_DNI,UNIVERSIDAD)
    VALUES(111222,25879);
INSERT INTO estudio(
    EMPLEADO_DNI,UNIVERSIDAD)
    VALUES(74522855,14785);
INSERT INTO estudio(
    EMPLEADO_DNI,UNIVERSIDAD)
    VALUES(222333,36985);
INSERT INTO estudio(
    EMPLEADO_DNI,UNIVERSIDAD)
    VALUES(16064451,05678);

-- CREAR UNA TABLA INFORMACION UNIVERSITARIA, COGIENDO LOS DATOS DE OTRAS TABLAS
CREATE TABLE INFO_UNIVERSITARIA(
    NOMBRE_COMPLETO VARCHAR(40),
    NOMBRE_UNIV VARCHAR(30)
);
SELECT * FROM info_universitaria;
INSERT INTO info_universitaria
    SELECT CONCAT(E.NOMBRE,' ',E.APELLIDO1,' ',E.APELLIDO2),U.NOMBRE_UNI 
    FROM empleados E
    JOIN estudio ES ON ES.`EMPLEADO_DNI`=E.`DNI`
    JOIN universidad U ON U.`UNIV_COD`=ES.`UNIVERSIDAD`;